// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// import 'firebase_options.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// // ...
// await Firebase.initializeApp(
//    options DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdeIZQMa_L1XUZvsGCPtMdDwcT-Q1qj_4',
    appId: '1:399396331071:web:23f79bf35565f2adec628a',
    messagingSenderId: '399396331071',
    projectId: 'meowpedia-a8bfe',
    authDomain: 'meowpedia-a8bfe.firebaseapp.com',
    storageBucket: 'meowpedia-a8bfe.firebasestorage.app',
    measurementId: 'G-FPKSYTNJ0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWVqFv2_j2wFo-z2FsqUtGlO4EtdYDVRw',
    appId: '1:399396331071:android:36191fa5ec10aefaec628a',
    messagingSenderId: '399396331071',
    projectId: 'meowpedia-a8bfe',
    storageBucket: 'meowpedia-a8bfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBinuFGjRv_5fjWaECNMIwsHxfxdsvcjkc',
    appId: '1:399396331071:ios:c5f8ee0a66a6a634ec628a',
    messagingSenderId: '399396331071',
    projectId: 'meowpedia-a8bfe',
    storageBucket: 'meowpedia-a8bfe.firebasestorage.app',
    iosBundleId: 'com.example.meowpedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBinuFGjRv_5fjWaECNMIwsHxfxdsvcjkc',
    appId: '1:399396331071:ios:c5f8ee0a66a6a634ec628a',
    messagingSenderId: '399396331071',
    projectId: 'meowpedia-a8bfe',
    storageBucket: 'meowpedia-a8bfe.firebasestorage.app',
    iosBundleId: 'com.example.meowpedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdeIZQMa_L1XUZvsGCPtMdDwcT-Q1qj_4',
    appId: '1:399396331071:web:9f63241aa71037b1ec628a',
    messagingSenderId: '399396331071',
    projectId: 'meowpedia-a8bfe',
    authDomain: 'meowpedia-a8bfe.firebaseapp.com',
    storageBucket: 'meowpedia-a8bfe.firebasestorage.app',
    measurementId: 'G-CK25CWRXVW',
  );
}
